apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  labels:
    app: unifi-controller
    class: wifi
  name: unifi-controller
spec:
  selector:
    matchLabels:
      app: unifi-controller
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unifi-controller
        class: wifi
    spec:
      containers:
      - image: drewgwallace/unifi:latest
        imagePullPolicy: IfNotPresent
        name: unifi-controller
        ports:
        - containerPort: 3478
          protocol: UDP
        - containerPort: 6789
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 8843
        - containerPort: 10001
          protocol: UDP
        # https://help.ubnt.com/hc/en-us/articles/115009221227-UniFi-Recommended-Minimum-System-Requirements
        resources:
          limits:
            cpu: "500m"
            memory: "2G"
        securityContext:
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/lib/unifi
          name: unifi-database-vol
        - mountPath: /var/log/unifi
          name: unifi-log-vol
      # nodeSelector:
        # kubernetes.io/hostname: NODE.EXAMPLE.COM
      restartPolicy: Always
      volumes:
      - name: unifi-database-vol
        hostPath:
          path: /opt/data/unifi/database
          type: DirectoryOrCreate
      - name: unifi-log-vol
        hostPath:
          path: /opt/data/unifi/logs
          type: DirectoryOrCreate
