apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: unifi-ingress
  namespace: "{{ namespace }}"
  labels:
    app: unifi-controller
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
  - host: {{ url }}
    http:
      paths:
      - backend:
          serviceName: unifi-service
          servicePort: 8443
  tls:
  - hosts:
    - {{ url }}
    secretName: {{ url_secret }}