apiVersion: v1
kind: Service
metadata:
  annotations: {}
  namespace: {{ namespace }}
  labels:
    app: unifi-controller
    class: wifi
  name: unifi-service
spec:
  ports:
  - name: "3478"
    port: 3478
    protocol: UDP
    targetPort: 3478
  - name: "6789"
    port: 6789
    targetPort: 6789
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "https"
    port: 8443
    targetPort: 8443
  - name: "8843"
    port: 8843
    targetPort: 8843
  - name: "10001"
    port: 10001
    protocol: UDP
    targetPort: 10001
  selector:
    app: unifi-controller
